### ISSUE TITLE
Does Cellpose support overlapping ROI?

### ISSUE THREAD

**Issue by 2454511550Lin** [kirkegaardlab/cellpose-overlap#1]
Hello, I am curious about the purpose of this dataset, I know cellpose does not have any parameter that can allow overlaps (which I am searching for alternatives because my dataset also has multiple overlaps). I am curious what's the model performance if trained on your dataset? Thank you.

**Comment by juliusbierk** [comment]
Hi! Please see https://github.com/kirkegaardlab/diffusionsplit and the associated paper.
(I'll update this repo with a link to that --- thank you!).

**Comment by juliusbierk** [comment]
@2454511550Lin and feel free to email if you want to try the code and have issues. :)
